{{- $values := .Values -}}
{{- range $index, $key := .Values.oracleKeys }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chain: aptos
    app: oracle
    should_scrape: scrape
    queue: {{ $key.queue }}
  name: aptos-{{ $key.queue }}-oracle-{{ $key.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        chain: aptos
        app: oracle
        queue: {{ $key.queue }}
        should_scrape: scrape
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - oracle
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
      # APTOS CONFIG
        - 
          name: CHAIN
          value: "aptos"
        - 
          name: APTOS_RPC_URL
          value: {{ $values.rpcUrl }}
        - 
          name: APTOS_PID
          value: {{ $values.pid }}
        - 
          name: APTOS_STATE_ADDRESS
          value: {{ $values.stateAddress }}
        - 
          name: APTOS_CRANK_ADDRESS
          value: {{ $values.crankAddress }}
      # ORACLE CONFIG
        - 
          name: APTOS_ORACLE_KEY
          value: {{ $key.data }}
        - 
          name: HEARTBEAT_INTERVAL
          value: {{ $values.heartbeatInterval | quote}}
      # SECRETS
        - 
          name: GOOGLE_PAYER_SECRET_PATH
          value: {{ $values.googlePayerSecretPath }}
        - 
          name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      # TASK RUNNER CONFIG
        - 
          name: TASK_RUNNER_SOLANA_RPC
          value: {{ $values.solanaMainnetRpc }}
        - 
          name: GCP_CONFIG_BUCKET
          value: {{ $values.gcpConfigBucket }}

      # MONITORING CONFIG
        - 
          name: METRICS_EXPORTER
          value: {{ $values.metricsExporter }}
        # - 
        #   name: PAGERDUTY_EVENT_KEY
        #   value: {{ $values.pagerdutyEventKey }}
      # IMAGE / RESOURCES
        image: {{ $values.image }}
        imagePullPolicy: Always
        name: aptos-oracle
        ports:
        - name: web
          containerPort: 9090
          protocol: TCP
        # livenessProbe:
          # httpGet:
            # path: /healthz
            # port: 8080
          # initialDelaySeconds: 30
          # periodSeconds: 3
        resources:
          limits:
            cpu: 2048m
            memory: 2048Mi
          requests:
            cpu: 2048m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      volumes:
      - name: google-cloud-key
        secret:
          secretName: oracle-service-account
---
{{ end }}

