cluster: $CLUSTER
googlePayerSecretPath: $GOOGLE_PAYER_SECRET_PATH
googleOracleSecretPath: $GOOGLE_PAYER_SECRET_PATH
metricsExporter: "prometheus"
gcpConfigBucket: "oracle-configs:configs.json"
rpcUrl: $RPC_URL
pagerdutyEventKey: $PAGERDUTY_EVENT_KEY
image: "docker.io/switchboardlabs/node:dev-v2-1-5-22a"
keyJson: $SERVICE_ACCOUNT_BASE64
oracleKeys:
  - name: idx-1
    data: $ORACLE_KEY
