server:
  scrape:
    enabled: true
    configMap: ""
    config:
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: "oracle-pods"
          kubernetes_sd_configs:
            - role: pod
          scheme: http
          metrics_path: /metrics
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: oracle
            action: keep
   